apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  replicas: {{ .Values.catalogApi.replicaCount }}
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done']
      containers:
        - name: catalog-api
          image: "{{ .Values.global.registry }}/catalog-api:{{ .Values.global.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__catalogdb
              value: "Host=postgres;Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ .Values.postgres.password }}"
            - name: ConnectionStrings__eventbus
              value: "amqp://{{ .Values.rabbitmq.username }}:{{ .Values.rabbitmq.password }}@rabbitmq"
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: "catalog-api"
          resources:
            {{- toYaml .Values.catalogApi.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
