apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: {{ .Values.catalogApi.service.type }}
  selector:
    app: catalog-api
  ports:
    - port: {{ .Values.catalogApi.service.port }}
      targetPort: {{ .Values.catalogApi.service.targetPort }}
